version: '3.8'

services:
  cart:
    build: .
    container_name: cart-frontend
    ports:
      - "3001:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
